version: "3.5"
services:
  postgres_ci:
    image: postgres:11
    container_name: postgres_ci
    environment:
      POSTGRES_DB: pvzddb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeit
    restart: unless-stopped
    networks:
      jenkins:
    volumes:
      - postgres_ci.data:/var/lib/postgresql/data

networks:
  jenkins:
    name: jenkins

volumes:
  postgres_ci.data:
    name: postgres_ci.data
